// <auto-generated />
using System;
using GeoExplorer.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Data.Migrations
{
    [DbContext(typeof(GeoExplorerDbContext))]
    [Migration("20260523220256_AddMultiplayerRooms")]
    partial class AddMultiplayerRooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoExplorer.Backend.Data.GameSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<int>("RoundCount")
                        .HasColumnType("integer")
                        .HasColumnName("round_count");

                    b.Property<int?>("RoundTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("round_time_seconds");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("Timed")
                        .HasColumnType("boolean")
                        .HasColumnName("timed");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.HasKey("Id");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.LocationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Clues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("clues");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("ImageAttribution")
                        .HasColumnType("text")
                        .HasColumnName("image_attribution");

                    b.Property<string>("ImageLicense")
                        .HasColumnType("text")
                        .HasColumnName("image_license");

                    b.Property<string>("ImageLicenseUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_license_url");

                    b.Property<string>("ImageSourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_source_url");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MediaSourceProvider")
                        .HasColumnType("text")
                        .HasColumnName("media_source_provider");

                    b.Property<DateOnly?>("MediaVerifiedAt")
                        .HasColumnType("date")
                        .HasColumnName("media_verified_at");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("SceneImage")
                        .HasColumnType("text")
                        .HasColumnName("scene_image");

                    b.Property<string>("SceneLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scene_label");

                    b.Property<string>("SceneNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scene_note");

                    b.Property<string>("StreetViewProvider")
                        .HasColumnType("text")
                        .HasColumnName("street_view_provider");

                    b.Property<string>("StreetViewUrl")
                        .HasColumnType("text")
                        .HasColumnName("street_view_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("VisualGradient")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("visual_gradient");

                    b.Property<string>("VisualSources")
                        .HasColumnType("jsonb")
                        .HasColumnName("visual_sources");

                    b.HasKey("Id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.MultiplayerGuessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_km");

                    b.Property<string>("GuessLabel")
                        .HasColumnType("text")
                        .HasColumnName("guess_label");

                    b.Property<double?>("GuessLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("guess_latitude");

                    b.Property<double?>("GuessLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("guess_longitude");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<string>("ResolutionReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resolution_reason");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("RoundId", "PlayerId")
                        .IsUnique();

                    b.ToTable("multiplayer_guesses", (string)null);
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.MultiplayerPlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Connected")
                        .HasColumnType("boolean")
                        .HasColumnName("connected");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "DisplayName")
                        .IsUnique();

                    b.HasIndex("RoomId", "PlayerId")
                        .IsUnique();

                    b.ToTable("multiplayer_players", (string)null);
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.MultiplayerRoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OwnerPlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_player_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_code");

                    b.Property<int>("RoundCount")
                        .HasColumnType("integer")
                        .HasColumnName("round_count");

                    b.Property<int?>("RoundTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("round_time_seconds");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("Timed")
                        .HasColumnType("boolean")
                        .HasColumnName("timed");

                    b.HasKey("Id");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("multiplayer_rooms", (string)null);
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.MultiplayerRoundEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_id");

                    b.Property<string>("ResolutionReason")
                        .HasColumnType("text")
                        .HasColumnName("resolution_reason");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("VisualSource")
                        .HasColumnType("jsonb")
                        .HasColumnName("visual_source");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("RoomId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("multiplayer_rounds", (string)null);
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.SessionRoundEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_km");

                    b.Property<string>("GuessLabel")
                        .HasColumnType("text")
                        .HasColumnName("guess_label");

                    b.Property<double?>("GuessLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("guess_latitude");

                    b.Property<double?>("GuessLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("guess_longitude");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_id");

                    b.Property<string>("ResolutionReason")
                        .HasColumnType("text")
                        .HasColumnName("resolution_reason");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("VisualSource")
                        .HasColumnType("jsonb")
                        .HasColumnName("visual_source");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SessionId");

                    b.ToTable("session_rounds", (string)null);
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.MultiplayerGuessEntity", b =>
                {
                    b.HasOne("GeoExplorer.Backend.Data.MultiplayerRoundEntity", "Round")
                        .WithMany("Guesses")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.MultiplayerPlayerEntity", b =>
                {
                    b.HasOne("GeoExplorer.Backend.Data.MultiplayerRoomEntity", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.MultiplayerRoundEntity", b =>
                {
                    b.HasOne("GeoExplorer.Backend.Data.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoExplorer.Backend.Data.MultiplayerRoomEntity", "Room")
                        .WithMany("Rounds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.SessionRoundEntity", b =>
                {
                    b.HasOne("GeoExplorer.Backend.Data.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoExplorer.Backend.Data.GameSessionEntity", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.GameSessionEntity", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.MultiplayerRoomEntity", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("GeoExplorer.Backend.Data.MultiplayerRoundEntity", b =>
                {
                    b.Navigation("Guesses");
                });
#pragma warning restore 612, 618
        }
    }
}
